# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-21 03:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
