# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-22 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapnewsHotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
