# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-21 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0002_auto_20190920_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MushroomSpot',
            new_name='NewsHotspot',
        ),
    ]
