# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-28 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0002_auto_20190921_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapnewshotspot',
            name='picture',
        ),
        migrations.AlterField(
            model_name='mapnewshotspot',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='mapnewshotspot',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
