# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0003_auto_20190928_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapnewshotspot',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
