# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0003_auto_20190928_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapnewshotspot',
            name='dia',
            field=models.IntegerField(null=True),
        ),
    ]
