# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-03 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0005_auto_20191001_1757'),
        ('mapnews', '0004_mapnewshotspot_dia'),
    ]

    operations = [
    ]
