# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-05 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnews', '0006_merge_20191003_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapnewshotspot',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapnewshotspot',
            name='tags',
            field=models.CharField(default='tags', max_length=256),
        ),
    ]
